name: Build Review Docker

# This workflow should only be called from workflow which is triggered on
# the "pull_request" event type. We should never dispatch this workflow from
# a "pull_request_target" event.

on:
  workflow_call:
    inputs:
      bypass_checks:
        type: boolean
        default: false
        description: Do not fail pipeline if checks failed
      enable_style_checks:
        type: boolean
        default: true
        description: Enable style_checks
      bypass_style_checks:
        type: boolean
        default: false
        description: Do not fail pipeline if style_checks failed
      enable_ort:
        type: boolean
        default: true
        description: Enable ORT scanning
      bypass_ort:
        type: boolean
        default: false
        description: Do not fail pipeline if ORT scan failed
      enable_trivy:
        type: boolean
        default: true
        description: Enable Trivy scanning
      bypass_trivy:
        type: boolean
        default: false
        description: Do not fail pipeline if Trivy failed
      image_name_suffix:
        type: string
        description: The suffix for the name of the Docker image
        default: test
        required: false
      image_repository:
        type: string
        description: The name of the Docker image repository
        default: ${{ github.repository }}
        required: false
      image_tag:
        type: string
        description: Docker image tag
        default: ${{ github.sha }}
        required: false

    outputs:
      image_registry:
        description: "Docker image registry"
        value: ${{ jobs.docker_build.outputs.image_registry }}
      image_repository:
        description: "Docker image repository"
        value: ${{ jobs.docker_build.outputs.image_repository }}
      image_tag:
        description: "Docker image tag"
        value: ${{ jobs.docker_build.outputs.image_tag }}

env:
  IMAGE_REGISTRY: ghcr.io

jobs:
  test:
    uses: ./.github/workflows/generic_docker_test.yml
    with:
      bypass_checks: ${{ inputs.bypass_checks }}
      enable_style_checks: ${{ inputs.enable_style_checks }}
      bypass_style_checks: ${{ inputs.bypass_style_checks }}
      enable_ort: ${{ inputs.enable_ort }}
      bypass_ort: ${{ inputs.bypass_ort }}
      ort_version: ${{ inputs.ort_version }}

  docker_build:
    runs-on: ubuntu-latest
    permissions:
      # `contents` for checkout code
      # `id-token` for ???
      # `security-events` for uploading trivy results to GHAS
      contents: read
      id-token: write
      security-events: write
    outputs:
        image_registry: ${{ env.IMAGE_REGISTRY }}
        image_repository: ${{ inputs.image_repository }}/${{ inputs.image_name_suffix }}
        image_tag: ${{ inputs.image_tag }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: true
          persist-credentials: false
      - uses: nepalevov/ai-dial-ci/actions/build_docker@main
        with:
          push: true
          push_ghcr: true
          image_name: ${{ env.IMAGE_REGISTRY }}/${{ inputs.image_repository }}/${{ inputs.image_name_suffix }}
          image_tag: ${{ inputs.image_tag }}
          scan: ${{ inputs.enable_trivy }}
          bypass_checks: ${{ inputs.bypass_trivy }}
