name: Generic Docker PR workflow

on:
  workflow_call:
    inputs:
      bypass_checks:
        type: boolean
        default: false
        description: Do not fail pipeline if checks failed
      enable_style_checks:
        type: boolean
        default: true
        description: Enable style_checks
      bypass_style_checks:
        type: boolean
        default: false
        description: Do not fail pipeline if style_checks failed
      enable_ort:
        type: boolean
        default: true
        description: Enable ORT scanning
      bypass_ort:
        type: boolean
        default: false
        description: Do not fail pipeline if ORT scan failed
      ort_version:
        type: string
        default: "latest"
        description: ORT version to use
      enable_trivy:
        type: boolean
        default: true
        description: Enable Trivy scanning
      bypass_trivy:
        type: boolean
        default: false
        description: Do not fail pipeline if Trivy failed
    outputs:
      image_tag:
        description: "Container image tag"
        value: ${{ jobs.docker_build.outputs.image_tag }}
      artifact_name:
        description: "A name for the artifact generated by the image build process, if exists"
        value: ${{ jobs.docker_build.outputs.artifact_name }}

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    uses: ./.github/workflows/generic_docker_test.yml
    with:
      bypass_checks: ${{ inputs.bypass_checks }}
      enable_style_checks: ${{ inputs.enable_style_checks }}
      bypass_style_checks: ${{ inputs.bypass_style_checks }}
      enable_ort: ${{ inputs.enable_ort }}
      bypass_ort: ${{ inputs.bypass_ort }}
      ort_version: ${{ inputs.ort_version }}

  docker_build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}
      artifact_name: ${{ steps.build.outputs.artifact_name }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: true
          persist-credentials: false
      - uses: nepalevov/ai-dial-ci/actions/build_docker@main
        id: build
        with:
          image_name: ghcr.io/${{ env.IMAGE_NAME }}
          image_tag: ${{ github.sha }}
          scan: ${{ inputs.enable_trivy }}
          bypass_checks: ${{ inputs.bypass_trivy }}
          upload_artifact: true
