name: Manage GitHub Environment

on:
  workflow_call:
    inputs:
      environment_name:
        type: string
        description: "The name of the GitHub environment to manage"
        required: false
      operation:
        type: string
        description: "The operation to perform on the GitHub environment. Can be one of `plan`, `create`, `delete`"
        required: true
      base_fqdn:
        type: string
        default: "gke.test.epam-rail.com"
        description: "The base FQDN for environment deployments"
        required: false
      environment_url:
        type: string
        description: "Overrides the environment URL, completely bypassing concatenation logic. Must follow RFC 3986"
        required: false
      reviewers:
        type: string
        default: '[{"type": "User", "id": 20123880}, {"type": "User", "id": 189285490}]' # TODO: change to epam/dial-contributors user group
        description: "A JSON-encoded list of user IDs or user-group IDs that will be designated as reviewers for the GitHub environment"
        required: false
      runs-on:
        type: string
        default: '["ubuntu-latest"]'
        description: "Overrides job runs-on settings (json-encoded list)"
        required: false
    secrets:
      ACTIONS_BOT_TOKEN:
        description: "GitHub token to perform actions on the GitHub environment. Required for `operation: create`, `operation: delete`"
        required: false
    outputs:
      environment_name:
        description: "The environment name"
        value: ${{ jobs.groundskeeper.outputs.environment_name }}
      environment_fqdn:
        description: "The environment FQDN"
        value: ${{ jobs.groundskeeper.outputs.environment_fqdn }}
      environment_url:
        description: "The environment URL"
        value: ${{ jobs.groundskeeper.outputs.environment_url }}

jobs:
  groundskeeper:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    outputs:
      environment_name: ${{ steps.settings.outputs.environment_name }}
      environment_url: ${{ steps.settings.outputs.environment_url }}
      environment_fqdn: ${{ steps.settings.outputs.environment_fqdn }}
    steps:
      - name: Update environment settings
        id: settings
        env:
          INPUT_ENVIRONMENT_NAME: ${{ inputs.environment_name }}
          INPUT_ENVIRONMENT_URL: ${{ inputs.environment_url }}
          INPUT_BASE_FQDN: ${{ inputs.base_fqdn }}
          INPUT_REPOSITORY: ${{ github.repository }}
          INPUT_SHA: ${{ github.sha }}
          INPUT_EVENT_NAME: ${{ github.event_name }}
          INPUT_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          #!/bin/bash

          # Name election
          if [ -n "$INPUT_ENVIRONMENT_NAME" ]; then
              environment_name=$INPUT_ENVIRONMENT_NAME
          elif [[ "$INPUT_EVENT_NAME" == "pull_request" ]] || [[ "$INPUT_EVENT_NAME" == "pull_request_target" ]]; then
              environment_name="pr-${INPUT_PR_NUMBER}"
          else
              environment_name=${INPUT_SHA:0:7}
          fi

          repository_name=${INPUT_REPOSITORY#*/}

          # URL election
          if [ -n "${INPUT_ENVIRONMENT_URL}" ]; then
              environment_url="${INPUT_ENVIRONMENT_URL}"
              environment_fqdn="${environment_url#*://}"
          else
              environment_fqdn="${repository_name}-${environment_name}.${INPUT_BASE_FQDN}"
              environment_url="https://${environment_fqdn}"
          fi

          echo "Environment name: ${environment_name}"
          echo "Repository name: ${repository_name}" # TODO: remove this after debug
          echo "Environment FQDN: ${environment_fqdn}"
          echo "Environment URL: ${environment_url}"

          echo "## Outputs"
          echo "| Property            | Value                        |" >>$GITHUB_STEP_SUMMARY
          echo "|---------------------|------------------------------|" >>$GITHUB_STEP_SUMMARY
          echo "| Environment name    | ${environment_name}          |" >>$GITHUB_STEP_SUMMARY
          echo "| Repository (full)   | ${INPUT_REPOSITORY}         |" >>$GITHUB_STEP_SUMMARY # TODO: remove this after debug
          echo "| Repository name     | ${repository_name}           |" >>$GITHUB_STEP_SUMMARY
          echo "| Environment FQDN    | ${environment_fqdn}          |" >>$GITHUB_STEP_SUMMARY
          echo "| Environment URL     | ${environment_url}           |" >>$GITHUB_STEP_SUMMARY

          echo "environment_name=${environment_name}" >>$GITHUB_OUTPUT
          echo "environment_fqdn=${environment_fqdn}" >>$GITHUB_OUTPUT
          echo "environment_url=${environment_url}" >>$GITHUB_OUTPUT

  create-or-update:
    if: ${{ inputs.operation == 'create' }}
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    needs:
      - groundskeeper
    steps:
      - name: Create or update an environment
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          INPUT_ENVIRONMENT_NAME: ${{ needs.groundskeeper.outputs.environment_name }}
          INPUT_REVIEWERS: ${{ inputs.reviewers }}
          GITHUB_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          debug: true
          script: |
            await github.request('PUT /repos/{owner}/{repo}/environments/{environment_name}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment_name: process.env.INPUT_ENVIRONMENT_NAME,
              wait_timer: 0,
              prevent_self_review: false,
              reviewers: JSON.parse(process.env.INPUT_REVIEWERS),
              headers: {
                'X-GitHub-Api-Version': '2022-11-28',
                'Accept': 'application/vnd.github+json'
              }
            });

  delete:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    if: ${{ inputs.operation == 'delete' }}
    needs:
      - groundskeeper
    steps:
      - name: "Cancel Workflow"
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # v0.12.1
        with:
          ignore_sha: true
          workflow_id: "all"
          access_token: ${{ secrets.ACTIONS_BOT_TOKEN }}
      - name: Sleep
        run: |
          # HACK: delay between workflow cancellation needed
          sleep 10
      - name: Delete environment
        uses: strumwolf/delete-deployment-environment@a4825dd9648c57da8437a4885c3fcad58beac69c # v3.0.0
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          environment: ${{ needs.groundskeeper.outputs.environment_name }}
