name: Gradle Dependency Submission

on:
  workflow_call:
    inputs:
      java_version:
        type: string
        description: "Java version to use"
        default: "17"
      java_distribution:
        type: string
        description: "Java distribution to use"
        default: "temurin"
      dependency_graph_action:
        type: string
        description: "Action to perform with dependency graph (generate-and-submit, generate-and-upload, download-and-submit)"
        default: "generate-and-submit"
        required: false

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          lfs: true
      - uses: nepalevov/ai-dial-ci/actions/java_prepare@main
        with:
          java_version: ${{ inputs.java_version }}
          java_distribution: ${{ inputs.java_distribution }}
      - name: Generate and save dependency graph
        uses: gradle/actions/dependency-submission@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
        with:
          dependency-graph: ${{ inputs.dependency_graph_action }}
